CREATE TABLE PERSON (
    PID INT,
    PNAME VARCHAR(25),
    PRIMARY KEY (PID)
)

CREATE TABLE CHAIRS (
    PID INT,
    DOCID INT,
    PRIMARY KEY (PID, DOCID)
)

CREATE TABLE GEDITS (
    DOCID INT,
    ISSUE_NO INT,
    PID INT,
    PRIMARY KEY (DOCID, ISSUE_NO, PID)
)

CREATE TABLE AUTHORS (
    PID INT,
    DOCID INT,
    PRIMARY KEY (PID, DOCID)
)

CREATE TABLE BOOK (
    DOCID INT,
    ISBN INT,
    PRIMARY KEY (DOCID)
)

CREATE TABLE JOURNAL_ISSUE (
    DOCID INT,
    ISSUE_NO INT,
    SCOPE [],
    PRIMARY KEY (DOCID, ISSUE_NO)
)

CREATE TABLE PROCEEDINGS (
    DOCID INT,
    CDATE [],
    CLOCATION [],
    CEDITOR [],
    PRIMARY KEY (DOCID)
)

CREATE TABLE JOURNAL_VOLUME (
    DOCID INT,
    VOLUME_NO INT,
    EDITOR VARCHAR(25),
    PRIMARY KEY (DOCID)
)

CREATE TABLE DOCUMENT (
    DOCID INT,
    TITLE [],
    PDATE [],
    PUBLISHERID [],
    PRIMARY KEY (DOCID)
)

CREATE TABLE PUBLISHER (
    PUBLISHERID INT,
    PUBNAME [],
    ADDRESS [],
    PRIMARY KEY (PUBLISHERID)
)

CREATE TABLE COPY (
    DOCID INT,
    COPYNO INT,
    BID INT,
    POSITION [],
    PRIMARY KEY (DOCID, COPYNO, BID)
)

CREATE TABLE BRANCH (
    BID INT,
    LNAME [],
    LOCATION [],
    PRIMARY KEY (BID)
)

CREATE TABLE BORROWING (
    BOR_NO INT,
    BDTIME [],
    RDTIME [],
    PRIMARY KEY (BOR_NO)
)

CREATE TABLE RESERVES (
    RID [],
    RESERVATION_NO [],
    DOCID [],
    COPYNO [],
    BID [],
    PRIMARY KEY (RESERVATION_NO, DOCID, COPYNO, BID)
)

CREATE TABLE RESERVATION (
    RES_NO [],
    DTIME [],
    PRIMARY KEY (RES_NO)
)

CREATE TABLE BORROWS (
    BOR_NO [],
    DOCID [],
    COPYNO [],
    BID [],
    RID [],
    PRIMARY KEY (BOR_NO, DOCID, COPYNO, BID)
)

CREATE TABLE READER (
    RID INT,
    RTYPE [],
    RNAME [],
    RADDRESS [],
    PHONE_NO [],
    PRIMARY KEY (RID)
);

-- CHAIRS table fk constraints
ALTER TABLE CHAIRS
ADD CONSTRAINT
FOREIGN KEY (PID)
REFERENCES PERSON(PID);

ALTER TABLE CHAIRS
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES PROCEEDINGS(DOCID);

-- GEDITS table FK constraints
ALTER TABLE GEDITS
ADD CONSTRAINT
FOREIGN KEY (PID)
REFERENCES PERSON(PID);

ALTER TABLE GEDITS
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES JOURNAL_ISSUE(DOCID);

ALTER TABLE GEDITS
ADD CONSTRAINT
FOREIGN KEY (ISSUE_NO)
REFERENCES JOURNAL_ISSUE(ISSUE_NO);

-- AUTHORS table FK constraints
ALTER TABLE AUTHORS
ADD CONSTRAINT
FOREIGN KEY (PID)
REFERENCES PERSON(PID);

ALTER TABLE AUTHORS
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES BOOK(DOCID);

-- JOURNAL_ISSUE
ALTER TABLE JOURNAL_ISSUE
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES JOURNAL_VOLUME(DOCID);

-- BOOK
ALTER TABLE BOOK
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES DOCUMENT(DOCID);

-- PROCEEDINGS
ALTER TABLE PROCEEDINGS
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES DOCUMENT(DOCID);

-- JOURNAL_VOLUME
ALTER TABLE JOURNAL_VOLUME
ADD CONSTRAINT
FOREIGN KEY (EDITOR)
REFERENCES PERSON(PID);

ALTER TABLE JOURNAL_VOLUME
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES DOCUMENT(DOCID);

-- DOCUMENT
ALTER TABLE DOCUMENT
ADD CONSTRAINT
FOREIGN KEY (PUBLISHERID)
REFERENCES PUBLISHER(PUBLISHERID);

-- COPY
ALTER TABLE COPY
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES DOCUMENT(DOCID);

ALTER TABLE COPY
ADD CONSTRAINT
FOREIGN KEY (BID)
REFERENCES BRANCH(BID);

-- RESERVES
ALTER TABLE RESERVES
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES COPY(DOCID);

ALTER TABLE RESERVES
ADD CONSTRAINT
FOREIGN KEY (COPYNO)
REFERENCES COPY(COPYNO);

ALTER TABLE RESERVES
ADD CONSTRAINT
FOREIGN KEY (BID)
REFERENCES COPY(BID);

ALTER TABLE RESERVES
ADD CONSTRAINT
FOREIGN KEY (RID)
REFERENCES READER(RID);

ALTER TABLE RESERVES
ADD CONSTRAINT
FOREIGN KEY (RESERVATION_NO)
REFERENCES RESERVATION(RES_NO);

-- BORROWS
ALTER TABLE BORROWS
ADD CONSTRAINT
FOREIGN KEY (DOCID)
REFERENCES COPY(DOCID);

ALTER TABLE BORROWS
ADD CONSTRAINT
FOREIGN KEY (COPYNO)
REFERENCES COPY(COPYNO);

ALTER TABLE BORROWS
ADD CONSTRAINT
FOREIGN KEY (BID)
REFERENCES COPY(BID);

ALTER TABLE BORROWS
ADD CONSTRAINT
FOREIGN KEY (BOR_NO)
REFERENCES BORROWING(BOR_NO);

ALTER TABLE BORROWS
ADD CONSTRAINT
FOREIGN KEY (RID)
REFERENCES READER(RID);
